[default]
CURRENT_ENV = "@jinja {{this.current_env | lower}}" # development or production
HOME_DIR = "@jinja {{env.HOME}}"
DIR_INPUT="Entrada"
APP_NAME="FastAPI! 🚀"
APP_VERSAO="1.0.0"
APP_DESCRIPTION="API Documentação ! 🇧🇷"

DIAS_SEMANA = [ "Segunda-feira", "Terça-feira", "Quarta-feira", "Quinta-feira", "Sexta-feira", "Sábado", "Domingo",]
